### ISSUE TITLE
"%n" string when the plugin is inserted

### ISSUE THREAD

**Issue by davenz** [generatorr/WorksheetPlugin#1]
Hello, 

Very useful plugin, thanks for the work!

When inserted, for some reason I see "%n" added to the page just above where the table is rendered. This is visible only when the page is saved, not in the JSPWiki markup itself.

Here is the markup I'm using:

```
!!!2013 Census meshblock dataset

Here is the result:

%%zebra-table
%%table-filter
[{WorksheetPlugin src='2013-mb-dataset-Area-Outside-Region-individual-part-3a.xlsx' sheetId='4' }]
/%
/%
```

And this is the saved page with this odd string highlighted:

![jspwiki-worksheetplugin-2](https://cloud.githubusercontent.com/assets/3925818/14101508/765400e8-f5f1-11e5-9ee8-d172c47ec634.png)

I'm using JSPWiki v2.10.2-svn-38. 

Cheers,
Dave

**Comment by generatorr** [comment]
true :-) thanks for the report. fixed with version 0.5-alpha
